# Use the .NET SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Debug
WORKDIR /src
COPY ["RadiSharp.csproj", "./"]
RUN dotnet restore "RadiSharp.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "RadiSharp.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Use the .NET Runtime image for running the application
FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "RadiSharp.dll"]

# Expose the port for the debugger
EXPOSE 5005

# Set the environment variable for the debugger
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development